name: Docker Image CI

on:
    # push:
    #     branches: ["main"]
    #     tags: ["v*"]
    #     paths:
    #         - "src/**"
    #         - "static/**"
    #         - "Dockerfile"
    #         - ".dockerignore"
    # pull_request:
    #     branches: ["main"]
    #     paths:
    #         - "src/**"
    #         - "static/**"
    #         - "Dockerfile"
    #         - ".dockerignore"
    # workflow_dispatch:
    release:
        types: [published, prereleased]

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write

        steps:
            - uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Extract metadata
              id: meta
              run: |
                if [[ "${{ github.event_name }}" == "push" ]]; then
                  echo "TAG_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
                elif [[ "${{ github.event_name }}" == "release" ]]; then
                  echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
                fi

            - name: Build and push
              uses: docker/build-push-action@v5.1.0
              with:
                  context: .
                  push: true
                  platforms: linux/amd64,linux/arm64
                  tags: makeplane/vert:${{ env.TAG_NAME }}
              env: 
                DOCKER_BUILDKIT: 1
                #   build-args: |
                #       PUB_ENV=production
                #       PUB_HOSTNAME=${{ vars.PUB_HOSTNAME || '' }}
                #       PUB_PLAUSIBLE_URL=${{ vars.PUB_PLAUSIBLE_URL || '' }}
                #       PUB_VERTD_URL=https://vertd.vert.sh
                #       PUB_DISABLE_ALL_EXTERNAL_REQUESTS=false
                #       PUB_DONATION_URL=https://donations.vert.sh
                #       PUB_STRIPE_KEY=pk_live_51RDVmAGSxPVad6bQwzVNnbc28nlmzA30krLWk1fefCMpUPiSRPkavMMbGqa8A3lUaOCMlsUEVy2CWDYg0ip3aPpL00ZJlsMkf2
